name: build
on:
  push:
  workflow_dispatch:
jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: android-actions/setup-android@v3
      - run: sdkmanager "ndk;26.1.10909125" "platforms;android-34" "build-tools;34.0.0"
      - run: git clone --recursive https://github.com/heiher/hev-socks5-tunnel app/src/main/jni/hev-socks5-tunnel
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.7
      - run: gradle assembleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: ShopeeProxy-apk
          path: app/build/outputs/apk/release/*.apk
